name: CI

on:
  push:
    branches: [ nocompile ]
  pull_request:
    branches: [ nocompile ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make test_all_make_targets
      run: make test_all_make_targets
    - name: make test
      run: make -j$(nproc) test
